[package]
name = "enigma"
version = "0.1.0"
authors = ["Flowmaster <inbox.733@gmail.com>"]
edition = "2018"

[dependencies]
#bitcoin = "0.16.0"
#iron = "*"
#rand = "0.6.5"
#router = "*"
#secp256k1 = "0.12.2"

env_logger = "0.5.3"
futures = "0.1.17"
hyper = "0.11.13"
log = "0.4.1"
