[package]
name = "enigma"
version = "0.1.0"
authors = ["Flowmaster <ellyssin.gimhae@gmail.com>"]
edition = "2018"

[dependencies]
bitcoin = "0.16.0"
iron = "*"
rand = "0.6.5"
router = "*"
secp256k1 = "0.12.2"
